<<<<<<< HEAD
services:
  - type: web
    name: neighborconnect-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
=======
services:
  - type: web
    name: neighborconnect-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
>>>>>>> 3dc65e7cba26a703c63e38d82ccff2cfbce780e2
